# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: helper.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'helper.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0chelper.proto\x12\x11\x61i_project_helper\" \n\x0bPlanRequest\x12\x11\n\tplan_text\x18\x01 \x01(\t\"\x95\x01\n\x0e\x41\x63tionFeedback\x12\x14\n\x0c\x61\x63tion_index\x18\x01 \x01(\x05\x12\x13\n\x0b\x61\x63tion_type\x18\x02 \x01(\t\x12\x18\n\x10step_description\x18\x03 \x01(\t\x12\x0e\n\x06status\x18\x04 \x01(\t\x12\x0e\n\x06output\x18\x05 \x01(\t\x12\r\n\x05\x65rror\x18\x06 \x01(\t\x12\x0f\n\x07\x63ommand\x18\x07 \x01(\t2a\n\rProjectHelper\x12P\n\x07RunPlan\x12\x1e.ai_project_helper.PlanRequest\x1a!.ai_project_helper.ActionFeedback\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'helper_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PLANREQUEST']._serialized_start=35
  _globals['_PLANREQUEST']._serialized_end=67
  _globals['_ACTIONFEEDBACK']._serialized_start=70
  _globals['_ACTIONFEEDBACK']._serialized_end=219
  _globals['_PROJECTHELPER']._serialized_start=221
  _globals['_PROJECTHELPER']._serialized_end=318
# @@protoc_insertion_point(module_scope)
